config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :categories, only: :index do
    resources :lessons, only: [:index, :new, :create, :show]
  end
  resources :relationships, only: [:create, :destroy]
  get 'home' => 'static_pages#index'
  namespace :admin do
    root 'categories#index'
    resources :categories, except: :show
    resources :words, except: :show
  end
  root 'users#index'

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :answers, inverse_of: :word
  has_many :lesson_words, inverse_of: :word

  accepts_nested_attributes_for :answers, allow_destroy: true
  accepts_nested_attributes_for :lesson_words, allow_destroy: true

  validates :category_id, presence: true
  validates :name, length: {minimum: 1, maximum:20}, presence: true
  validates :mean, length: {minimum: 1, maximum:20}, presence: true

  scope :random_with_number, ->number do
    where.not(id: LessonWord.select(:word_id)
    .where(answer: Answer.correct)).sample number
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController

  def index
    @words = Word.paginate page: params[:page], per_page: 10
  end

  def new
    @word = Word.new
    @word.answers.build
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:message] = "Word was created successfully..."
      redirect_to admin_words_path
    else
      render :new
    end
  end

  def edit
    @word = Word.find params[:id]
  end

  def update
    @word = Word.find params[:id]
    if @word.update word_params
      flash[:message] = "Word was updated successfully..."
      redirect_to admin_words_path
    else
      render :edit
    end
  end

  def destroy
    @word = Word.find params[:id]
    if @word.destroy
      flash[:message] = "Word was deleted successfully..."
    else
      flash[:message] = "Word was deleted failure..."
    end
    redirect_to admin_words_path
  end

  private
  def word_params
    params.require(:word).permit :category_id, :name, :mean,
      answers_attributes: [:id, :name, :correct, :_destroy]
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @words = Word.all
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    if @word.save
      flash[:message] = 'Word was created successfully...'
    else
      flash[:message] = 'Word was created failure...'
    end
    redirect_to new_word_path
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(word_params)
      flash[:message] = 'Word was updated successfully...'
    else
      flash[:message] = ' Word was updated failure...'
    end
    redirect_to edit_word_path
  end

  def destroy
    @word = Word.find(params[:id])
    if @word.destroy
      flash[:message] = 'Word was deleted successfully...'
    else
      flash[:message] = 'Word was deleted failure...'
    end
    redirect_to words_path
  end

  private
    def word_params
      params.require(:word).permit(:category_id, :name, :mean)
    end

end

app/views/admin/words/_fields.html.erb
<%= render "layouts/messages", object: f.object %>
<div class="form-group">
  <%= f.label :Categories %>
  <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: false}, {class: "form-control"} %>
</div>
<div class="form-group">
  <%= f.label :Name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Input name..." %>
</div>
<div class="form-group">
  <%= f.label :Mean %>
  <%= f.text_field :mean, class: "form-control", placeholder: "Input mean..." %>
</div>
<div id="answer" class="form-group">
  <%= f.label :Answer %>
  <div class="controls">
    <%= f.fields_for :answers do |answer_form| %>
      <%= answer_form.text_field :name, class: "form-control", placeholder: "Input answer..." %>
      <%= answer_form.select :correct, [["Incorrect", 0], ["Correct", 1]], {}, class: "form-control" %>
      <%= answer_form.link_to_remove "Remove", class: "btn btn-danger" %>
    <% end %>
  </div>
  <%= f.link_to_add "Add a answer", :answers, class: "btn btn-success" %>
</div>

app/views/admin/words/edit.html.erb
<h2>Update</h2>
<%= nested_form_for [:admin, @word] do |f| %>
  <%= render "fields", f: f %>
  <%= f.submit "Update", class: "btn btn-success" %>
<% end %>

app/views/admin/words/index.html.erb
<h2>Words</h2>
<%= render "layouts/message" %>
<%= link_to "Add new", new_admin_word_path %>
<table class="table table-bordered">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Mean</th>
    <th>Category</th>
    <th>Action</th>
  </tr>
  <% if @words.blank? %>
    <tr>
      <td colspan="5">Data not found!!!</td>
    </tr>
  <% end %>
  <% @words.each do |word| %>
    <tr>
      <td><%= word.id %></td>
      <td><%= link_to word.name, edit_admin_word_path(word) %></td>
      <td><%= word.mean %></td>
      <td><%= word.category.name %></td>
      <td><%= link_to "Delete", admin_word_path(word), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/admin/words/new.html.erb
<h2>Add new</h2>
<%= nested_form_for [:admin, @word] do |f| %>
  <%= render "fields", f: f %>
  <%= f.submit "Create", class: "btn btn-success" %>
<% end %>