config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :categories, only: :index do
    resources :lessons, only: [:index, :new, :create, :show]
  end
  resources :relationships, only: [:create, :destroy]
  get 'home' => 'static_pages#index'
  namespace :admin do
    root 'categories#index'
    resources :categories, except: :show
    resources :words, except: :show
  end
  root 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  STATUS = %w(0, 1)

  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :users, through: :lessons

  validates :name, length: {minimum: 3, maximum:20}, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  def index
    @categories = Category.paginate page: params[:page], per_page: 10
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:message] = "Category was created successfully..."
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update category_params
      flash[:message] = "Category was updated successfully..."
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find params[:id]
    if @category.destroy
      flash[:message] = "Category was deleted successfully..."
    else
      flash[:message] = "Category was deleted failure..."
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :status)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.paginate page: params[:page], per_page: 10
  end

end

app/views/admin/categories/_fields.html.erb
<%= render "layouts/messages", object: f.object %>
<div class="form-group">
  <%= f.label :Name %>
  <%= f.text_field :name, class: "form-control", placeholder: "Input name..." %>
</div>
<div class="form-group">
  <%= f.label :Status %>
  <%= f.select :status, [["Active", 1], ["InActive", 0]], {}, class: "form-control" %>
</div>

app/views/admin/categories/edit.html.erb
<h2>Update</h2>
<%= form_for [:admin, @category] do |f| %>
  <%= render "fields", f: f %>
  <%= f.submit "Update", class: "btn btn-success" %>
<% end %>

app/views/admin/categories/index.html.erb
<h2>Categories</h2>
<%= render "layouts/message" %>
<%= link_to "Add new", new_admin_category_path %>
<table class="table table-bordered">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  <% if @categories.blank? %>
    <tr>
      <td colspan="5">Data not found!!!</td>
    </tr>
  <% end %>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= link_to category.name, edit_admin_category_path(category) %></td>
      <td><%= category.status == Category::STATUS.first.to_i ? "InActive" : "Active" %></td>
      <td><%= link_to "Delete", admin_category_path(category), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @categories %>

app/views/admin/categories/new.html.erb
<h2>Add new</h2>
<%= form_for [:admin, @category] do |f| %>
  <%= render "fields", f: f %>
  <%= f.submit "Create", class: "btn btn-success" %>
<% end %>