config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :categories, only: :index do
    resources :lessons, only: [:index, :new, :create, :show]
  end
  resources :relationships, only: [:create, :destroy]
  get 'home' => 'static_pages#index'
  namespace :admin do
    root 'categories#index'
    resources :categories, except: :show
    resources :words, except: :show
  end
  root 'users#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  STATUS = %w(0, 1)

  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :users, through: :lessons

  validates :name, length: {minimum: 3, maximum:20}, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  def index
    @categories = Category.paginate page: params[:page], per_page: 10
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:message] = "Category was created successfully..."
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update category_params
      flash[:message] = "Category was updated successfully..."
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find params[:id]
    if @category.destroy
      flash[:message] = "Category was deleted successfully..."
    else
      flash[:message] = "Category was deleted failure..."
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name, :status)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.paginate page: params[:page], per_page: 10
  end

end

app/views/categories/_form.html.erb
<% if flash[:message] %>
  <p class="bg-danger"><%= flash[:message] %></p>
<% end %>
<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :Name %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Input name...' %>
  </div>
  <div class="form-group">
    <%= f.label :Status %>
    <%= f.select :status, [['Active', 1], ['InActive', 0]], {}, class: 'form-control' %>
  </div>
  <%= f.submit 'Save', class: 'btn btn-success' %>
<% end %>

app/views/categories/edit.html.erb
<h2>Update</h2>
<%= render 'form' %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <div class="bs-callout bs-callout-info">
    <h4><%= category.name %></h4>
    <span class="category_count">You've learned
      <% if !current_user.lessons.filter_by_category(category.id).first.blank? %>
        <%= current_user.lessons.filter_by_category(category.id).sum :result %>
      <% else %>
        0
      <% end %>
      / <%= category.words.count %>
    </span><br>
    <%= link_to "Start", new_category_lesson_path(category), class: "btn" %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h2>Add new</h2>
<%= render 'form' %>