config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :categories, only: :index do
    resources :lessons, only: [:index, :new, :create, :show]
  end
  resources :relationships, only: [:create, :destroy]
  get 'home' => 'static_pages#index'
  namespace :admin do
    root 'categories#index'
    resources :categories, except: :show
    resources :words, except: :show
  end
  root 'users#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if !logged_in? %>
          <li>
            <%= link_to "Signin", new_session_path %>
          </li>
        <% else %>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              Categories
              <%= content_tag :span, "", class: "caret" %>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Show all", admin_categories_path %></li>
              <li><%= link_to "Add new", new_admin_category_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              Words
              <%= content_tag :span, "", class: "caret" %>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Show all", admin_words_path %></li>
              <li><%= link_to "Add new", new_admin_word_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              Users
              <%= content_tag :span, "", class: "caret" %>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Show all", users_path %></li>
              <li><%= link_to "Add new", new_user_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
              <%= current_user.fullname %>
              <%= content_tag :span, "", class: "caret" %>
            <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li class="dropdown-header"><%= link_to "Sign out", session_path(current_user), method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_message.html.erb
<% if flash[:message] %>
  <p class="bg-primary"><%= flash[:message] %></p>
<% end %>

app/views/layouts/_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <p class="bg-danger"><%= message %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container starter-template">
    <%= yield %>
  </div>
  <script type="text/javascript">
    $.fn.words.init()
  </script>
</body>
</html>